server:
  port: 4000 # 포트번호 추천받아요

spring:
  # 이메일
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username} # 이메일을 보내는 주최
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 - 기본값 false
          timeout: 5000
          starttls:
            enable: true

  # 레디스 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  # 데이터베이스 설정
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: ${ddl.auto}

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

# 로그 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace


# 파일 업로드 경로 설정
file:
  upload:
    url: ${file.url}
    path: ${file.path}

# OPEN DOC API 설정
springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/v1/**

  # JWT 설정
member:
  jwt:
    secret: ${jwt.secret}
    validTime: ${jwt.validTime}